### ISSUE TITLE
Possible user experience improvement for 4. Show cost information by neighborhood and room type

### ISSUE THREAD

**Issue by jazminvaleriano** [PythonDataScience24/AirBnB-Dataset-Reporting-Tool#3]
I did a few tests with your tool, and I have some suggestions for option `4. Show cost information by neighborhood and room type`;
 - I realized the tool is case sensitive, so if I wrote the neighborhood or room type in all lower or uppercase, the tool did not recognize it. It might improve the experience for the user if a) There was a warning telling them to keep an eye on upper/lowercase, or b) turn the code into case-insensitive. 
 - It might be a good idea to add a validation for e.g. 'neighborhood not found', or 'room type not valid', because sometimes I had to double check to see if I had some typo or if there was really no info available in the dataset. 

Keep it up, your project looks very good so far!

**Comment by susanneliskova** [comment]
thank you, we fixed the issue.
